{
 "title": "INT statistics teste",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "src",
    "label": "Src ip",
    "query": "SHOW TAG VALUES FROM flow_latency WITH KEY = src_ip\n"
   },
   {
    "name": "flow",
    "label": "Flow Label",
    "query": "SHOW TAG VALUES FROM flow_latency WITH KEY = flow_label\n"
   },
   {
    "name": "dst",
    "label": "Dst ip",
    "query": "SHOW TAG VALUES FROM flow_latency WITH KEY = \"dst_ip\"\n"
   },
   {
    "name": "switch_id",
    "label": "Switch ID",
    "query": "SHOW TAG VALUES FROM \"switch_stats\" WITH KEY = \"switch_id\"\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Packet number/size per flow",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "flow_label::tag" ], "type": "tag" },
      { "params": [ "dst_ip::tag" ], "type": "tag" },
      { "params": [ "src_ip::tag" ], "type": "tag" }
     ],
     "measurement": "flow_latency",
     "query": "SELECT  count(size) AS \"Number of Packet\", last(\"size\") AS \"Packet Size\" FROM \"flow_stats\" WHERE $timeFilter GROUP BY \"flow_label\"::tag, \"dst_ip\"::tag, \"src_ip\"::tag",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number/percentage of packets per switch",
   "type": "piechart",
   "description": "(Default last 10 minutes, depends on the set time range from the dashboard itself)",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "switch 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "switch 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "switch 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "switch 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "4" }
     ]
    },
    {
     "alias": "switch 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "switch 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "6" }
     ]
    },
    {
     "alias": "switch 7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "switch 8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "8" }
     ]
    },
    {
     "alias": "switch 9",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "9" }
     ]
    },
    {
     "alias": "switch 10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "10" }
     ]
    },
    {
     "alias": "switch 11",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "11" }
     ]
    },
    {
     "alias": "switch 12",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "12" }
     ]
    },
    {
     "alias": "switch 13",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "13" }
     ]
    },
    {
     "alias": "switch 14",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "14" }
     ]
    }
   ]
  },
  {
   "title": "Switch Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 7 },
   "targets": [
    {
     "alias": "s1",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "s2",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "s3",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "s4",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "4" }
     ]
    },
    {
     "alias": "s5",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "s6",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "6" }
     ]
    },
    {
     "alias": "s7",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "s8",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "8" }
     ]
    },
    {
     "alias": "s9",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "9" }
     ]
    },
    {
     "alias": "s10",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "10" }
     ]
    },
    {
     "alias": "s11",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "11" }
     ]
    },
    {
     "alias": "s12",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "12" }
     ]
    },
    {
     "alias": "s13",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "13" }
     ]
    },
    {
     "alias": "s14",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "switch_stats",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "switch_id::tag", "operator": "=", "value": "14" }
     ]
    }
   ]
  },
  {
   "title": "Packet Size by Switch",
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flow_latency",
     "query": "SELECT sum(\"size\") AS \"Packet Size (bytes)\" FROM \"switch_stats\" WHERE $timeFilter GROUP BY \"flow_label\", \"dst_ip\", \"src_ip\", \"switch_id\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processed data per switch",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 15 },
   "targets": [
    {
     "query": "SELECT sum(\"size\") AS \"Total Packet Size (bytes)\" FROM \"switch_stats\" WHERE $timeFilter GROUP BY \"switch_id\""
    }
   ]
  },
  {
   "title": "Flow Latency ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "src: $tag_src_ip dst: $tag_dst_ip flow: $tag_flow_label",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flow_latency",
     "query": "SELECT moving_average(mean(\"latency\"), 10)\nFROM \"switch_stats\"\nWHERE $timeFilter\nGROUP BY time(1s), \"dst_ip\", \"src_ip\", \"flow_label\"\n\n",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Link Latency",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flow_latency",
     "query": "SELECT * FROM \"link_latency\" WHERE $timeFilter  ORDER BY time DESC\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}